local QUICKEYS = Root().ShowData.DataPools.Default.Quickeys

local function CreateQuickey(number, code)
    QUICKEYS:Create(number)
    QUICKEYS[number]:Set("NAME", code)
    QUICKEYS[number]:Set("CODE", code)
    QUICKEYS[number]:Set("LOCK", true)
end


local function main()
    CreateQuickey(125, 'NUM0')
    CreateQuickey(126, 'NUM1')
    CreateQuickey(127, 'NUM2')
    CreateQuickey(128, 'NUM3')
    CreateQuickey(129, 'NUM4')
    CreateQuickey(130, 'NUM5')
    CreateQuickey(131, 'NUM6')
    CreateQuickey(132, 'NUM7')
    CreateQuickey(133, 'NUM8')
    CreateQuickey(134, 'NUM9')
    CreateQuickey(135, 'PLEASE')
    CreateQuickey(136, 'ESC')
    CreateQuickey(137, 'DOT')
    CreateQuickey(138, 'THRU')
    CreateQuickey(139, 'CLEAR')
    CreateQuickey(140, 'PLUS')
    CreateQuickey(141, 'MINUS')
    CreateQuickey(142, 'SLASH')
    CreateQuickey(143, 'ASTERISK')
    CreateQuickey(144, 'MACRO')
    CreateQuickey(145, 'SEQUENCE')
    CreateQuickey(146, 'SELECT')
    CreateQuickey(147, 'OFF')
    CreateQuickey(148, 'ON')
    CreateQuickey(149, 'ASSIGN')
    CreateQuickey(150, 'GO')
    CreateQuickey(151, 'GOBACK')
    CreateQuickey(152, 'GOFAST')
    CreateQuickey(153, 'GOBACKFAST')
    CreateQuickey(154, 'OOPS')
    CreateQuickey(155, 'CUE')
    CreateQuickey(156, 'CHANNEL')
    CreateQuickey(157, 'GROUP')
    CreateQuickey(158, 'PRESET')
    CreateQuickey(159, 'SELFIX')
    CreateQuickey(160, 'AT')
    CreateQuickey(161, 'FULL')
    CreateQuickey(162, 'STORE')
    CreateQuickey(163, 'PAGE_UP')
    CreateQuickey(164, 'PAGE_DOWN')
    CreateQuickey(165, 'UPDATE')
    CreateQuickey(166, 'ALIGN')
    CreateQuickey(167, 'IF')
    CreateQuickey(168, 'EDIT')

end


return main
